# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Minsu Kim
description: >- # this means to ignore newlines until "baseurl:"
  Bay is a minimal Jekyll Theme.
baseurl: # the subpath of the site
url: https://kms040411.github.io # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
# google_analytics: "UA-121636368-3"

header:
  pages:
    #- name: Home
    #  slug: /
    #- name: Work
    #- name: Blog

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: mskim@casys.kaist.ac.kr
      link: mailto:mskim@casys.kaist.ac.kr
    - name: Email
      value: kms040411@kaist.ac.kr
      link: mailto:kms040411@kaist.ac.kr
  follow:
    - name: GitHub
      link: http://github.com/kms040411

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 7
